### ISSUE TITLE
Problems scanning items classified as Volumes in Comicvine

### ISSUE THREAD

**Issue by Hoplake** [hmhrex/Tenma#25]
I have stuff like Escape from New York - Volume 1 and 2. 

While other comics have their id in comicvine url starting with 4000-comicid, these Escape from New York volumes have urls like 4050-comicid.

Now if I tell Tenma that Escape from New York - Escape From Florida - Volume 1 has an id of 86530 and hit reprocess it will get the info of a Dick Tracy comic which has an id of 4000-86530 (and my intended comic had id of 4050-86530).

**Comment by hmhrex** [comment]
4050 is actually a "Volume" ID. It's where collected "Issues" are found. For instance, on the [page you're mentioning](https://comicvine.gamespot.com/escape-from-new-york-escape-from-florida/4050-86530/), if you click on the that issue, you'll get your 4000 "Issue" ID.

This is a poor descriptor on Comic Vine's part. Issues and Collected Volumes are both considered "Issues" in Comic Vine, but they are also organized separately into different "Volumes". For example, the Escape From New York tradebacks are [collected on this page](https://comicvine.gamespot.com/escape-from-new-york/4050-78563/), but the first collected volume is [collected on this page](https://comicvine.gamespot.com/escape-from-new-york-escape-from-florida/4050-86530/).

Sorry for the confusion! I'm hoping to better the matching over time so that this kind of confusion can be avoided.
